function convert(s: string, numRows: number): string {
  if (numRows === 1) return s
  let maxGap = numRows * 2 - 2
  const rArray = []
  let currentIndex = 0
  let nextIndex = 0
  let isNextIndex = false
  let num = 1
  let row = 0
  while (row++ < numRows) {
    while (currentIndex < s.length) {
      rArray.push(s[currentIndex])
      if (isNextIndex) {
        if (num % 2 === 0) {
          currentIndex += nextIndex
        } else {
          currentIndex += maxGap
        }
        num++
      } else {
        currentIndex += maxGap
      }
    }
    maxGap -= 2
    nextIndex += 2
    isNextIndex = true
    if (maxGap === 0) {
      maxGap = numRows * 2 - 2
      nextIndex = 0
      isNextIndex = false
    }
    num = 1
    currentIndex = row
  }
  return rArray.join('')
}
console.log(
  convert(
    'PAYPALISHIRPAPYAIPASRPASRPASRIRGAHNPLNAARIYAAPPYLRRAPLIHIIRAPLIHIIRAPLIHIILSIINNPYSIIGNAAIIGPYPLIIGPAPYIAHPRPAYIIRIGNAYIIRIGNAYIIRIGNAHNNAPAPSRPIPYISPPAPSIRNYALAHPILPAYAYPISGRAGAPISGRAGAPISGRAGAIAGAASARIPPIPIHPASARSGGLYHLIAAIPLPYLANHAIAGSANHAIAGSANHAIAGSRAISYRLYNIAIANIIYRLGHAPHPIIGLASPIPPHLAIANSPHLAIANSPHLAIANSPPISPRPGILGIYNLYRIPGIAISAIANSIAHPRPALINRAGAASINRAGAASINRAGAASNAASARSYPIPIINPIARSGRAYHLIHGSPIRPAPASIIPNPYISIIPNPYISIIPNPYIGPYILIHAALAHSIALLIHNIPPSIRIGHRRAAPAPHRNIPYPLHRNIPYPLHRNIPYPLPYPLIHIPYALSHRYAIHIINGAISIRNIPYYIGAAIGAAIGAAAASRPIIPSRGLHIPYAIPASRPASRPASRIRGAHNPLNAARIYAAPPYLRRAPLIHIIRAPLIHIIRAPLIHIILSIINNPYSIIGNAAIIGPYPLIIGPAPYIAHPRPAYIIRIGNAYIIRIGNAYIIRIGNAHNNAPAPSRPIPYISPPAPSIRNYALAHPILPAYAYPISGRAGAPISGRAGAPISGRAGAIAGAASARIPPIPIHPASARSGGLYHLIAAIPLPYLANHAIAGSANHAIAGSANHAIAGSRAISYRLYNIAIANIIYRLGHAPHPIIGLASPIPPHLAIANSPHLAIANSPHLAIANSPPISPRPGILGIYNLYRIPGIAISAIANSIAHPRPALINRAGAASINRAGAASINRAGAASNAASARSYPIPIINPIARSGRAYHLIHGSPIRPAPASIIPNPYISIIPNPYISIIPNPYIGPYILIHAALAHSIALLIHNIPPSIRIGHRRAAPAPHRNIPYPLHRNIPYPLHRNIPYPLPYPLIHIPYALSHRYAIHIINGAISIRNIPYYIGAAIGAAIGAAAASRPIIPSRGLHIPYAIPASRPASRPASRIRGAHNPLNAARIYAAPPYLRRAPLIHIIRAPLIHIIRAPLIHIILSIINNPYSIIGNAAIIGPYPLIIGPAPYIAHPRPAYIIRIGNAYIIRIGNAYIIRIGNAHNNAPAPSRPIPYISPPAPSIRNYALAHPILPAYAYPISGRAGAPISGRAGAPISGRAGAIAGAASARIPPIPIHPASARSGGLYHLIAAIPLPYLANHAIAGSANHAIAGSANHAIAGSRAISYRLYNIAIANIIYRLGHAPHPIIGLASPIPPHLAIANSPHLAIANSPHLAIANSPPISPRPGILGIYNLYRIPGIAISAIANSIAHPRPALINRAGAASINRAGAASINRAGAASNAASARSYPIPIINPIARSGRAYHLIHGSPIRPAPASIIPNPYISIIPNPYISIIPNPYIGPYILIHAALAHSIALLIHNIPPSIRIGHRRAAPAPHRNIPYPLHRNIPYPLHRNIPYPLPYPLIHIPYALSHRYAIHIINGAISIRNIPYYIGAAIGAAIGAAAASRPIIPSRGLHIYPAPAYPALISHIRPARPAYPAPAYPALIRPAYPAPAYPALIRPAYPAPAYPALISHIRPAYPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGGPAYPALISHSHIRPAYPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGGPAYPALISHSHIRPAYPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGGPAYPALISHYPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGGPAYPALISHIRPAYPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGGYPALISHIRPAYPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGGPALISHIRINGPAYPALISHIRINGIPAYPALISHIRINGNPAYPALISHIRINGG',
    1000
  )
)
